--Borrado de tablas

drop table procesos_admision cascade constraints;
drop table personas cascade constraints;
drop table tipos_documento cascade constraints;
drop table tipos_identificacion cascade constraints;
drop table tipos_proceso cascade constraints;
drop table estados_civil cascade constraints;
drop table entrevistas cascade constraints;
drop table convenios cascade constraints;
drop table estados_validacion cascade constraints;
drop table grupos_etnicos cascade constraints;
drop table refs_personal_familiar cascade constraints;
drop table homologaciones cascade constraints;
drop table ubicaciones_geograficas cascade constraints;
drop table educaciones cascade constraints;
drop table inscripciones cascade constraints;
drop table migrations cascade constraints;
drop table modalidades cascade constraints;
drop table password_resets cascade constraints;
drop table detalle_entrevistas cascade constraints;
drop table documentos cascade constraints;
drop table preguntas cascade constraints;
drop table respuestas cascade constraints;
drop table validaciones cascade constraints;

drop table tasks;
drop table users;

drop sequence "SIUP"."CONVENIOS_ID_CONVENIO_SEQ";
drop sequence "SIUP"."ENTREVISTAS_ID_ENTREVISTA_SEQ";
drop sequence "SIUP"."ESTADOS_CIVIL_ID_ESTADO_CIVIL_";
drop sequence "SIUP"."ESTADOS_VALIDACION_ID_ESTADO_S";
drop sequence "SIUP"."GRUPOS_ETNICOS_ID_GRUPO_ETNICO";
drop sequence "SIUP"."INSCRIPCIONES_ID_INSCRIPCION_S";
drop sequence "SIUP"."MODALIDADES_ID_MODALIDAD_SEQ";
drop sequence "SIUP"."TASKS_ID_SEQ";
drop sequence "SIUP"."TIPOS_DOCUMENTO_ID_TIPO_DOCUME";
drop sequence "SIUP"."TIPOS_IDENTIFICACION_ID_TIPO_I";
drop sequence "SIUP"."TIPOS_PROCESO_ID_TIPO_PROCESO_";
drop sequence "SIUP"."USERS_ID_SEQ";
drop sequence "SIUP"."DETALLE_ENTREVISTAS_ID_DETALLE";
drop sequence "SIUP"."DOCUMENTOS_ID_DOCUMENTO_SEQ";
drop sequence "SIUP"."PREGUNTAS_ID_PREGUNTA_SEQ";
drop sequence "SIUP"."PROCESOS_ADMISION_ID_PROCESO_A";
drop sequence "SIUP"."RESPUESTAS_ID_RESPUESTA_SEQ";
drop sequence "SIUP"."VALIDACIONES_ID_VALIDACION_SEQ";
drop sequence "SIUP"."HOMOLOGACIONES_ID_HOMOLOGACION";
drop sequence "SIUP"."EDUCACIONES_ID_EDUCACION_SEQ";
drop sequence "SIUP"."UBICACIONES_GEOGRAFICAS_ID_UBI";
drop sequence "SIUP"."REFS_PERSONAL_FAMILIAR_ID_REFE";